"""Offline smoke test — GitHub calls are stubbed, so no token or network needed.

    python test_smoke.py
"""

import json

from fastapi.testclient import TestClient

import file_builder
import github_client
import main
import readme_updater
from schema import Submission

PAYLOAD = {
    "problem_id": 1,
    "title": "Two Sum",
    "slug": "two-sum",
    "difficulty": "Easy",
    "tags": ["Array", "Hash Table"],
    "runtime_ms": 52,
    "memory_mb": 14.3,
    "runtime_percentile": 87.5,
    "memory_percentile": 72.1,
    "code": "class Solution:\n    def twoSum(self, nums, target):\n        return []",
}

# ------------------------------------------------------------------ stubs

committed = {}
readme_state = {
    "content": readme_updater.SEED_README
    + "\n_Generated by lc-autosync._\n",
}


def fake_commit(submission: Submission) -> str:
    path = file_builder.resolve_path(submission)
    committed[path] = file_builder.build_content(submission)
    return f"https://github.com/user/leetcode-solutions/blob/main/{path}"


def fake_upsert(submission: Submission) -> None:
    current = readme_state["content"]
    before, _, rest = current.partition(readme_updater.START)
    block, _, after = rest.partition(readme_updater.END)
    rows = readme_updater._existing_rows(block)
    rows[submission.problem_id] = readme_updater.build_row(submission)
    readme_state["content"] = before + readme_updater._render_block(rows) + after


main.github_client.commit_solution = fake_commit
main.readme_updater.upsert_row = fake_upsert

# ------------------------------------------------------------------ run

client = TestClient(main.app)


def check(label, condition):
    print(f"  {'PASS' if condition else 'FAIL'}  {label}")
    assert condition, label


print("\n1. path + content")
sub = Submission(**PAYLOAD)
path = file_builder.resolve_path(sub)
check(f"path == topics/array/0001_two_sum.py (got {path})", path == "topics/array/0001_two_sum.py")
content = file_builder.build_content(sub)
check("header contains padded id", "0001. Two Sum" in content)
check("header contains percentiles", "beats 87.5%" in content and "beats 72.1%" in content)
check("code follows header", content.strip().endswith("return []"))

print("\n2. POST /submit")
r = client.post("/submit", json=PAYLOAD)
check(f"status 200 (got {r.status_code})", r.status_code == 200)
check("status ok", r.json()["status"] == "ok")
check("file committed", path in committed)

print("\n3. duplicate guard")
r2 = client.post("/submit", json=PAYLOAD)
check("second post within 10s -> duplicate", r2.json()["status"] == "duplicate")

print("\n4. validation")
bad = {k: v for k, v in PAYLOAD.items() if k != "code"}
r3 = client.post("/submit", json=bad)
check(f"missing field -> 400 (got {r3.status_code})", r3.status_code == 400)
check("names the field", "code" in r3.json()["message"])

print("\n5. README upsert")
second = dict(PAYLOAD, problem_id=42, title="Trapping Rain Water", slug="trapping-rain-water",
              difficulty="Hard", tags=["Array", "Two Pointers"], runtime_ms=88)
main._recent.clear()
client.post("/submit", json=second)
readme = readme_state["content"]
check("row 1 present", "| 1 | [Two Sum]" in readme)
check("row 42 present", "| 42 | [Trapping Rain Water]" in readme)
check("sorted ascending", readme.index("| 1 | [Two Sum]") < readme.index("| 42 |"))
check("text below table preserved", "_Generated by lc-autosync._" in readme)

# re-submit problem 1 with new stats -> replaces, does not duplicate
main._recent.clear()
client.post("/submit", json=dict(PAYLOAD, runtime_ms=40, runtime_percentile=99.1))
readme = readme_state["content"]
check("no duplicate row for 1", readme.count("[Two Sum](") == 1)
check("row updated in place", "40ms (99.1%)" in readme)

print("\nREADME now:\n")
print(readme_state["content"])
print("\nCommitted file:\n")
print(committed[path])
print("All checks passed.")
